blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'
urlpatterns = [
    path('', post_list, name='post_list_url'),
    path('post/create/', PostCreate.as_view(), name='post_create_url'),
    path('post/<str:slug>/', PostDetail.as_view(), name='post_detail_url'),
    path('post/<str:slug>/update/', PostUpdate.as_view(), name='post_update_url'),
    path('post/<str:slug>/delete/', PostDelete.as_view(), name='post_delete_url'),
    path('tags/', tag_list, name='tag_list_url'),
    path('tag/create/', TagCreate.as_view(), name='tag_create_url'),
    path('tag/<str:slug>/', TagDetail.as_view(), name='tag_detail_url'),
    path('tag/<str:slug>/update/', TagUpdate.as_view(), name='tag_update_url'),
    path('tag/<str:slug>/delete/', TagDelete.as_view(), name='tag_delete_url'),
]

normal_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import redirect_blog
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', redirect_blog),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from time import time

from django.contrib.auth.models import User
from django.db import models
from django.shortcuts import reverse
from django.utils.text import slugify


def gen_slug(s):
    new_slug = slugify(s, allow_unicode=True)
    return new_slug + '-' + str(int(time()))


class Post(models.Model):
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    title = models.CharField('Заголовок', max_length=50, db_index=True)
    slug = models.SlugField('url', max_length=50, unique=True, blank=True)
    body = models.TextField('Тело', blank=True, db_index=True)
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    tags = models.ManyToManyField('Tag', blank=True, related_name='posts', verbose_name='Тег')
    image = models.ImageField('Изображение', upload_to='post/', null=True, blank=True)
    published = models.BooleanField('Опубликовать?', default=True)
    viewed = models.PositiveIntegerField('Просмотернно', default=0)

    def get_absolute_url(self):
        return reverse('blog:post_detail_url', kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse('blog:post_update_url', kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('blog:post_delete_url', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = gen_slug(self.title)
        super().save(*args, **kwargs)

    def get_comments_count(self):
        return self.comments.count()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Tag(models.Model):
    title = models.CharField('Тег', max_length=50)
    slug = models.SlugField('url', max_length=50, unique=True)
    published = models.BooleanField('Отображать?', default=True)

    def get_absolute_url(self):
        return reverse('blog:tag_detail_url', kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse('blog:tag_update_url', kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('blog:tag_delete_url', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'


class Comment(models.Model):
    body = models.TextField('Комментарий')
    create_date = models.DateTimeField('Дата создания', auto_now=True)
    moderation = models.BooleanField(default=True)
    post = models.ForeignKey(
        Post,
        verbose_name='Пост',
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.body

    class Meta:
        ordering = ['-create_date']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

blog/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Post, Tag, Comment


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['title', 'slug']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'slug': forms.TextInput(attrs={'class': 'form-control'})
        }

    def clean_slug(self):
        new_slug = self.cleaned_data['slug'].lower()
        if new_slug == 'create':
            raise ValidationError('Slug may not be "Create"')
        elif Tag.objects.filter(slug__iexact=new_slug).count():
            raise ValidationError('Slug must be unique. We have "{}" slug already'.format(new_slug))
        return new_slug


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'slug', 'body', 'tags']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'slug': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
            'tags': forms.SelectMultiple(attrs={'class': 'form-control'}),
        }

    def clean_slug(self):
        new_slug = self.cleaned_data['slug'].lower()

        if new_slug == 'create':
            raise ValidationError('Slug may not be "Create"')
        return new_slug


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']

        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control', 'rows': 4, 'cols': 40})
        }

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, redirect
from django.views.generic import View

from blog.models import Post, Tag
from .forms import TagForm, PostForm, CommentForm
from .utils import ObjectDetailMixin, ObjectCreateMixin, ObjectUpdateMixin, ObjectDeleteMixin


def post_list(request):
    search_query = request.GET.get('search', '')

    if search_query:
        posts = Post.objects.filter(
            Q(title__icontains=search_query) |
            Q(body__icontains=search_query),
            published=True
        )
    else:
        posts = Post.objects.filter(published=True)

    paginator = Paginator(posts, 3)
    page_number = request.GET.get('page', 1)
    page = paginator.get_page(page_number)
    is_paginated = page.has_other_pages()
    if page.has_previous():
        previous_url = '?page={}'.format(page.previous_page_number())
    else:
        previous_url = ''

    if page.has_next():
        next_url = '?page={}'.format(page.next_page_number())
    else:
        next_url = ''

    context = {
        'page_object': page,
        'is_paginated': is_paginated,
        'next_url': next_url,
        'previous_url': previous_url
    }
    return render(request, 'blog/index.html', context)


def tag_list(request):
    tags = Tag.objects.filter(published=True)
    return render(request, 'blog/tag_list.html', context={'tags': tags})


class PostDetail(ObjectDetailMixin, View):
    model = Post
    template = 'blog/post_detail.html'
    model_form = CommentForm
    raise_exception = True

    def post(self, request, slug):
        form = CommentForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.post = Post.objects.get(slug__iexact=slug)
            form.author = request.user
            form.save()
        return redirect(request.path)


class PostCreate(LoginRequiredMixin, ObjectCreateMixin, View):
    model_form = PostForm
    template = 'blog/post_create.html'
    raise_exception = True


class PostUpdate(LoginRequiredMixin, ObjectUpdateMixin, View):
    model = Post
    model_form = PostForm
    template = 'blog/post_update.html'
    raise_exception = True


class PostDelete(LoginRequiredMixin, ObjectDeleteMixin, View):
    model = Post
    template = 'blog/post_delete.html'
    redirect_url = 'blog:post_list_url'
    raise_exception = True


class TagDetail(ObjectDetailMixin, View):
    model = Tag
    template = 'blog/tag_detail.html'


class TagCreate(LoginRequiredMixin, ObjectCreateMixin, View):
    model_form = TagForm
    template = 'blog/tag_create.html'
    raise_exception = True


class TagUpdate(LoginRequiredMixin, ObjectUpdateMixin, View):
    model = Tag
    model_form = TagForm
    template = 'blog/tag_update.html'
    raise_exception = True


class TagDelete(LoginRequiredMixin, ObjectDeleteMixin, View):
    model = Tag
    template = 'blog/tag_delete.html'
    redirect_url = 'blog:tag_list_url'
    raise_exception = True

blog/templates/blog/base_blog.html
{% extends 'base.html' %}

{% block admin-panel %}

    <div class="btn-group">
        <button type="button" class="btn btn-dark dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false">
            Создать
        </button>
        <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'blog:post_create_url' %}">Пост</a>
            <a class="dropdown-item" href="{% url 'blog:tag_create_url' %}">Тег</a>
        </div>
    </div>

    <a href="{{ admin_object.get_update_url }}" class="btn btn-dark edit"
       style="{% if detail %}display: block;{% endif %}">Обновить</a>
    <a href="{{ admin_object.get_delete_url }}" class="btn btn-danger delete"
       style="{% if detail %}display: block;{% endif %}">Удалить</a>

{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base_blog.html' %}
{% load menu_tags %}
{% block title %}
    Список постов
{% endblock %}


{% block content %}

    <h1 class="mb-5">Посты:</h1>
    {% for post in page_object.object_list %}
        {% include 'blog/includes/post_card_template.html' %}
    {% endfor %}

    {% if is_paginated %}
        <nav aria-label="...">
            <ul class="pagination">
                <li class="page-item {% if not previous_url %} disabled {% endif %}">
                    <a class="page-link" href="{{ previous_url }}" tabindex="-1" aria-disabled="true">Назад</a>
                </li>

                {% for n in page_object.paginator.page_range %}

                    {% if page_object.number == n %}
                        <li class="page-item active" aria-current="page">
                            <a class="page-link" href="?page={{ n }}">{{ n }}<span class="sr-only"></span></a>
                        </li>
                    {% elif n > page_object.number|add:-3 and n < page_object.number|add:3 %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ n }}">{{ n }}</a>
                        </li>
                    {% endif %}
                {% endfor %}


                <li class="page-item {% if not next_url %} disabled {% endif %}">
                    <a class="page-link" href="{{ next_url }}" tabindex="-1" aria-disabled="true">Вперед</a>
                </li>
            </ul>
        </nav>
    {% endif %}

{% endblock %} content %}

blog/templates/blog/post_create.html
{% extends 'blog/base_blog.html' %}


{% block title %}
    Создать пост - {{ block.super }}
{% endblock %}


{% block content %}
    <form action="{% url 'blog:post_create_url' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                {% if field.errors %}
                    <div class="alert alert-danger">
                        {{ field.errors }}
                    </div>
                {% endif %}
                {{ field.label }}
                {{ field }}
            </div>
        {% endfor %}

        <button class="btn btn-dark mb-3" type="submit" name="button">Создать</button>

    </form>
{% endblock %}

blog/templates/blog/post_delete.html
{% extends 'blog/base_blog.html' %}

{% block title %}
    Удалить пост "{{ post.title|title }}" - {{ block.super }}
{% endblock %}


{% block content %}

    <form action="{{ post.get_delete_url }}" method="post">
        {% csrf_token %}

        <h3>Вы уверены, что хотите удалить <b>"{{ post.title|title }}"</b> пост?</h3>
        <a href="{{post.get_absolute_url}}">Отменить</a>
        <button type="submit" name="button" class="btn btn-danger">Удалить</button>
    </form>
    
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base_blog.html' %}


{% block title %}
    {{ post.title }} - {{ block.super }}
{% endblock %}


{% block content %}
    <h1 class="mt-5">
        {{ post.title }}
    </h1>
    <div class="box">
        <p>
            {{ post.body }}
        </p>
    </div>

    <h4>Комментарии:</h4>
    {% if user.is_authenticated %}
        <form action="" method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    {{ field }}
                </div>
            {% endfor %}

            <button class="btn btn-dark" type="submit" name="button">Отправить</button>

        </form>
    {% else %}
        <p>Что бы оставить комментарий войдите на сайт</p>
    {% endif %}
    <hr>
    {% for comment in post.comments.all %}
        Пользователь - {{ comment.author }}<br>
        {{ comment.body }} <br>
        Добавлен - {{ comment.create_date }}<br><br>
    {% endfor %}

{% endblock %}

blog/templates/blog/post_update.html
{% extends 'blog/base_blog.html' %}


{% block title %}
    Обновить пост - {{ block.super }}
{% endblock %}


{% block content %}
    <form action="{{ post.get_update_url }}" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                {% if field.errors %}
                    <div class="alert alert-danger">
                        {{ field.errors }}
                    </div>
                {% endif %}
                {{ field.label }}
                {{ field }}
            </div>
        {% endfor %}

        <button class="btn btn-dark mb-3" type="submit" name="button">Обновить</button>

    </form>
{% endblock %}

blog/templates/blog/tag_create.html
{% extends 'blog/base_blog.html' %}

{% block title %}
    Создать тег - {{ block.super }}
{% endblock %}

{% block content %}
    <form action="{% url 'blog:tag_create_url' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                {% if field.errors %}
                    <div class="alert alert-danger">
                        {{ field.errors }}
                    </div>
                {% endif %}
                {{ field.label }}
                {{ field }}
            </div>
        {% endfor %}

        <button class="btn btn-dark" type="submit" name="button">Создать</button>

    </form>
{% endblock %}

blog/templates/blog/tag_delete.html
{% extends 'blog/base_blog.html' %}

{% block title %}
    Удалить тег "{{ tag.title|title }}" - {{ block.super }}
{% endblock %}


{% block content %}

    <form action="{{ tag.get_delete_url }}" method="post">
        {% csrf_token %}

        <h3>Вы уверены, что хотите удалить<b>"{{ tag.title|title }}" тег?</b></h3>
        <a href="{{tag.get_absolute_url}}">Cancel</a>
        <button type="submit" name="button" class="btn btn-danger">Удалить</button>
    </form>
    
{% endblock %}

blog/templates/blog/tag_detail.html
{% extends 'blog/base_blog.html' %}


{% block title %}
    {{ tag.title }} - {{ block.super }}
{% endblock %}


{% block content %}
    <h1 class="mb-5">Посты с тегом "{{ tag.title|title }}":</h1>
    {% for post in tag.posts.all %}
        {% include 'blog/includes/post_card_template.html' %}
    {% endfor %}

{% endblock %}

blog/templates/blog/tag_list.html
{% extends 'blog/base_blog.html' %}

{% block title %}
    Список тегов
{% endblock %}


{% block content %}
    <h1 class="mb-5">Теги:</h1>
    {% for tag in tags %}
        <h3><a href="{{ tag.get_absolute_url }}">{{ tag.title }}</a></h3>
    {% endfor %}

{% endblock %}

blog/templates/blog/tag_update.html
{% extends 'blog/base_blog.html' %}

{% block title %}
    Обновить тег - {{ block.super }}
{% endblock %}

{% block content %}
    <form action="{{ tag.get_update_url }}" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                {% if field.errors %}
                    <div class="alert alert-danger">
                        {{ field.errors }}
                    </div>
                {% endif %}
                {{ field.label }}
                {{ field }}
            </div>
        {% endfor %}

        <button class="btn btn-dark" type="submit" name="button">Обновить</button>

    </form>
{% endblock %}