blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'
urlpatterns = [
    path('', post_list, name='post_list_url'),
    path('post/create/', PostCreate.as_view(), name='post_create_url'),
    path('post/<str:slug>/', PostDetail.as_view(), name='post_detail_url'),
    path('post/<str:slug>/update/', PostUpdate.as_view(), name='post_update_url'),
    path('post/<str:slug>/delete/', PostDelete.as_view(), name='post_delete_url'),
    path('tags/', tag_list, name='tag_list_url'),
    path('tag/create/', TagCreate.as_view(), name='tag_create_url'),
    path('tag/<str:slug>/', TagDetail.as_view(), name='tag_detail_url'),
    path('tag/<str:slug>/update/', TagUpdate.as_view(), name='tag_update_url'),
    path('tag/<str:slug>/delete/', TagDelete.as_view(), name='tag_delete_url'),
]

normal_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import redirect_blog
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', redirect_blog),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static menu_tags %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>
        {% block title %}
            Блог
        {% endblock %}
    </title>
</head>
<body>

<nav class="navbar navbar-dark bg-dark avbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Блог</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'blog:post_list_url' %}">Посты</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:tag_list_url' %}">Теги</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Меню
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% menu_item menu='Main' %}
                </div>
            </li>
            {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        Участие
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% menu_item menu='Volk' %}
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="http://127.0.0.1:5000/accounts/logout/">Выход</a>
                </li>

            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="http://127.0.0.1:5000/accounts/login/">Вход</a>
                </li>
            {% endif %}


        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url 'blog:post_list_url' %}">
            <input class="form-control mr-sm-2" type="search" placeholder="Поиск" aria-label="Search" name="search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Поиск</button>
        </form>
    </div>
</nav>

<div class="container mt-5">
    <div class="row">
        <div class="col-6 offset-md-2">
            {% block content %}
                Здесь нет контента для вас.
            {% endblock %}
        </div>
    </div>
</div>

{% if request.user.is_authenticated and request.user.is_staff %}

    <div class="admin-panel align-items-center">
        <a href="/admin" class="btn btn-outline-info">Админка</a>
        {% block admin-panel %}{% endblock %}
    </div>

{% endif %}

<footer class="py-4 bg-dark text-white-50">
    <div class="text-center">
        <a href="mailto:mr.vol4onok@gmail.com">
            <small>mr.vol4onok@gmail.com</small>
        </a>
    </div>
</footer>

</body>
</html>